# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('photo', models.ImageField(upload_to='profile/img')),
                ('education_level', models.CharField(max_length=30)),
                ('date_since_joining', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
