# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_skills', models.CharField(max_length=40)),
                ('vocational_skills', models.CharField(max_length=200)),
                ('further_education', models.CharField(max_length=100)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.PersonalInfo')),
            ],
        ),
    ]
