# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_placementdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelterlife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField()),
                ('avgexpense', models.IntegerField(max_length=6)),
                ('savings', models.IntegerField(max_length=6)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.PersonalInfo')),
            ],
        ),
    ]
