# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_shelterlife'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=20)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('natureofactivity', models.CharField(max_length=100)),
                ('noofwomen', models.IntegerField(max_length=100)),
                ('expectedoutcome', models.CharField(max_length=100)),
                ('obtainedoutcome', models.CharField(max_length=100)),
                ('amountspend', models.IntegerField(max_length=6)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.PersonalInfo')),
            ],
        ),
    ]
