# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20170708_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
