# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_personalinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
