# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20170709_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='dob',
        ),
    ]
