# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_remove_personalinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
