# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20170709_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='contact',
            field=models.CharField(default='email', max_length=20),
            preserve_default=False,
        ),
    ]
