# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20170709_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.CharField(max_length=10),
        ),
    ]
