# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20170709_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile/img'),
        ),
    ]
