# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_remove_personalinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='salary',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='savings',
            field=models.CharField(max_length=6),
        ),
    ]
